"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-10-07
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fw_version', sa.String(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_version', sa.Integer(), nullable=False),
    sa.Column('schedule_acked_version', sa.Integer(), nullable=False),
    sa.Column('last_msg_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingested_messages',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('msg_id', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('device_id', 'msg_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('attending_doctor_id', sa.String(), nullable=True),
    sa.Column('wristband_rfid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wristband_rfid')
    )
    op.create_table('staff',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('rfid_uid', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('rfid_uid')
    )
    op.create_table('vitals',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Float(precision=24), nullable=True),
    sa.Column('nurse_id', sa.String(), nullable=True),
    sa.Column('news2', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ts', 'device_id')
    )
    op.create_table('admissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('bed', sa.String(), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('ai_suggested', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_confirmed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['human_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_patient_id'), 'ai_summaries', ['patient_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('news2', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ai_suggested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acked_by', sa.String(), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('referral_text', sa.Text(), nullable=False),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('urgency_ai', sa.Integer(), nullable=False),
    sa.Column('urgency_final', sa.Integer(), nullable=True),
    sa.Column('ai_suggested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_confirmed_by', sa.String(), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('slot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_show_prob', sa.Float(), nullable=True),
    sa.Column('patient_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['human_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_patient_id'), 'notes', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('care_plan', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('med_doses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prescription_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_of_day', sa.String(), nullable=False),
    sa.Column('meds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('taken_method', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_med_doses_patient_id'), 'med_doses', ['patient_id'], unique=False)
    # ### end Alembic commands ###

    # users <-> patients reference each other, so this FK is added once both tables exist
    op.create_foreign_key('fk_users_patient_id', 'users', 'patients', ['patient_id'], ['id'])
    op.execute("SELECT create_hypertable('vitals', 'ts', if_not_exists => TRUE)")
    op.create_index("ix_vitals_patient_ts", "vitals", ["patient_id", sa.text("ts DESC")])
    op.execute("CREATE UNIQUE INDEX uq_adm_active_patient ON admissions(patient_id) WHERE discharged_at IS NULL")
    op.execute("CREATE UNIQUE INDEX uq_adm_active_device ON admissions(device_id) "
               "WHERE discharged_at IS NULL AND device_id IS NOT NULL")


def downgrade() -> None:
    op.drop_constraint('fk_users_patient_id', 'users', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_med_doses_patient_id'), table_name='med_doses')
    op.drop_table('med_doses')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_notes_patient_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_table('appointments')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_summaries_patient_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_table('admissions')
    op.drop_table('vitals')
    op.drop_table('staff')
    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('ingested_messages')
    op.drop_table('devices')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
